### ISSUE TITLE
Mob AI disabled

### ISSUE THREAD

**Issue by bstar16** [RemainingToast/2b2tau-issues#2]

**Comment by RemainingToast** [comment]
Mhm can you report which mobs exactly? I have tested donkey and zombie and their both work

**Comment by L-Nadav** [comment]
So far ive seen llamas, cows, pigs I think and a couple of others I can't remember off the top of my head. the don't take knock of fall down. Unless, in the llamas case, they are ridden.

**Comment by RemainingToast** [comment]
I see no issues, both with spawned in entities and naturally generated entities.

**Comment by RemainingToast** [comment]
The problem was caused by previously installed mob optimiser plugin and the AI had only been disabled for existing mobs while the plugin existed.
